namespace OposedApi.Error
{
    public enum Errors
    {
        USER_NOT_FOUND = 100,
        USER_BLOCKED = 101,
        USER_EXPIRATED_PASSWORD = 102,
        USER_INVALID_PASSWORD = 103,
        AUTHKEY_NOT_FOUND = 200,
        AUTHKEY_INVALID = 201,
        PERMISSIONS_FAILED = 202,
        RESOURCE_NOT_FOUND = 300,
        RESOURCE_DELETING_FAILED = 301,
        RESOURCE_UPDATING_FAILED = 302,
        EVENT_NOT_FOUND = 400,
        EVENT_DELETING_FAILED = 401,
        EVENT_UPDATING_FAILED = 402,
        EVENT_INSERT_FAILED = 403,
        TEMPLATE_NOT_FOUND = 500,
        TEMPLATE_DELETING_FAILED = 501,
        TEMPLATE_UPDATING_FAILED = 502,
        ROOM_NOT_FOUND = 600,
        ROOM_DELETING_FAILED = 601,
        ROOM_UPDATING_FAILED = 602,
        ROOM_TEMPLATE_FAILED = 603,
        NEWSLETTER_UPDATING_FAILED = 700
    }
}
